# Generated by Django 4.2.1 on 2023-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='identification',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
