# Generated by Django 4.2.1 on 2023-05-15 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('salary', models.BigIntegerField()),
                ('work_days', models.IntegerField()),
                ('clasification', models.CharField(choices=[('MOI', 'MOI'), ('MOD', 'MOD')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_dl', models.BigIntegerField(default=0)),
                ('salary_il', models.BigIntegerField(default=9)),
                ('benefits_dl', models.BigIntegerField(default=0)),
                ('benefits_il', models.BigIntegerField(default=0)),
                ('security_dl', models.BigIntegerField(default=0)),
                ('security_il', models.BigIntegerField(default=0)),
                ('parafiscal_dl', models.BigIntegerField(default=0)),
                ('parafiscal_il', models.BigIntegerField(default=0)),
                ('totalsalary', models.BigIntegerField(default=0)),
                ('totalbenefits', models.BigIntegerField(default=0)),
                ('totalsecurity', models.BigIntegerField(default=0)),
                ('totalparafiscal', models.BigIntegerField(default=0)),
                ('datepayroll', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(to='authentication.employee')),
            ],
        ),
    ]
