# Generated by Django 4.2.1 on 2023-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ateb',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='box',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='health',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='icbf',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sena',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='severance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='severance_pay',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='totalbenefits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='totalparafiscal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='totalsecurity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacations',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary_il',
            field=models.BigIntegerField(default=0),
        ),
    ]
