# Generated by Django 4.2.1 on 2023-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_employee_ateb_employee_bonus_employee_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='totalsalary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_aux',
            field=models.BigIntegerField(default=0),
        ),
    ]
