# Generated by Django 4.2.1 on 2023-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_employee_totalsalary_employee_transport_aux'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salarydev',
            field=models.BigIntegerField(default=0),
        ),
    ]
