# Generated by Django 4.2.1 on 2023-05-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_employee_salarydev'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deduction',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='ret',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='totalpaysalary',
            field=models.BigIntegerField(default=0),
        ),
    ]
