# Generated by Django 4.2.1 on 2023-05-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_employee_ret'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
